module SFXWorldcat
  SFX_HOST = ENV['SFX_HOST']
  SFX_PORT = ENV['SFX_PORT']
  SFX_USER = ENV['SFX_USER']
  SFX_PASS = ENV['SFX_PASS']
  SFX_GLOBAL_DATABASE = ENV['SFX_GLOBAL_DATABASE']
  SFX_LOCAL_DATABASE = ENV['SFX_LOCAL_DATABASE']
  WORLDCAT_URL = ENV['WORLDCAT_URL']
  READ_URL = ENV['WORLDCAT_READ_URL']
  WORLDCAT_API_KEY = ENV['WORLDCAT_API_KEY']
end
